### ISSUE TITLE
Figure out deployment

### ISSUE THREAD

**Issue by intarga** [metno/rove#17]

**Comment by lcoram** [comment]
What part of the deployment? like how it will run as a vm or a pod on k8s?

**Comment by intarga** [comment]
This can wait until we're both back in Oslo, no rush. I'm thinking as barebones as we can do on ostack

**Comment by lcoram** [comment]
Its easy to make a VM in some flavour of Ubuntu to mess around on to start off with, I guess the question is if at some point we have to make it with Ansible for reproduceability.
